### ISSUE TITLE
Consider a license change

### ISSUE THREAD

**Issue by Quick-Flash** [blackbox-log/blackbox-log#104]
GPLv3 is a very restrictive license for a crate. LGPL license which is quite similar to GPL would be much better as a library as it wouldnt force any project that uses it to adopt GPLv3.

**Comment by wetheredge** [comment]
Agreed. I'd prefer to use the Apache 2.0 + MIT dual license typical for Rust crates, but much of the code was written *very* closely based on `blackbox_decode` and the blackbox encoding parts of BF, INAV, etc which are all GPLv3. The GPL faq is [pretty clear](https://www.gnu.org/licenses/gpl-faq.html#TranslateCode) that ports/translations need to stay under the same license. Perhaps the overall algorithm I use is different enough from `blackbox_decode` that it is novel work not simply a port but that is not a distinction I feel qualified to make.

Perhaps @thenickdude who wrote much/most of `blackbox_decode` could weigh in?

**Comment by thenickdude** [comment]
This looks like substantial enough of a rewrite that I doubt the original license from my code applies any more.

The main licensing concern in blackbox_decode was that it included a copy/paste of imu.c from Baseflight which itself derived from GPLv3 MultiWii, but that doesn't seem to be present here?

**Comment by Quick-Flash** [comment]
@wetheredge aside from bot commits this is the only commit you did not write. https://github.com/blackbox-log/blackbox-log/commit/48d5271d3e97892f6d5fc6982f4e168e6fc588c6

And I would agree with thenickdude that you wouldnt be forced to use GPLv3 as this is enough of a new work rather than just a derivative work.

**Comment by wetheredge** [comment]
I'll publish v0.4.0 with the new license soon.
