### ISSUE TITLE
Correct attributions.

### ISSUE THREAD

**Issue by hydra** [blackbox-log/blackbox-log#89]
Hiya,

Firstly, cool project. Nice to see the rust implementation!

Secondly, Can you please correct/update the attributions of the project in the Readme?

Blackbox logging was written by Nicholas Sherlock ( @thenickdude ).

The original Blackbox logging was from here:

https://github.com/thenickdude/blackbox

It was first widely used in Cleanflight here:

https://github.com/cleanflight/cleanflight/pull/227
https://github.com/cleanflight/cleanflight/blob/master/docs/Blackbox.md

Betaflight and iNAV only have blackbox because they forked Cleanflight.

Betaflight has since made some minor additions/improvements, but the bulk of the code still in use today was written by the original author, Nicholas Sherlock who deserves some credit/attribution and, IMHO, the history/prior-art section should be updated to include the links above and a mention of Nick.

Cheers!

**Comment by hydra** [comment]
Also FYI, this Go library correctly attributes Cleanflight - https://github.com/maxlaverse/blackbox-library 😄

**Comment by wetheredge** [comment]
Good call. If that PR looks good to you I'll go ahead and merge.

Also, out of curiosity, how'd you come across my project?

**Comment by hydra** [comment]
> Good call. If that PR looks good to you I'll go ahead and merge.

Looks perfect, thanks.  I'm sure Nick will be happy too.

> Also, out of curiosity, how'd you come across my project?

I did a google search for 'rust blackbox' and it came up.
